build:
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
            tests:
                override:
                    - php-scrutinizer-run

filter:
    excluded_paths:
        - 'assets/*.min.js'
    dependency_paths:
        - wordpress/

checks:
    php:
        code_rating: true
        duplication: true
