services:
  db:
    image: mariadb:12.2@sha256:350261292d0129fd4b24f537dcf05ecd3ebe34d39d5b592af551f38310e7a167
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      wp:
        ipv4_address: 172.25.0.3

  wordpress:
    image: wordpress:apache@sha256:5d2c212561c4b5442ebc4d98933a9cbadcf3dee8888ed3fd9ed44667c27cc905
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      wp:
        ipv4_address: 172.25.0.2
    volumes:
      - .:/var/www/html/wp-content/plugins/ww-yubico-otp

volumes:
  db:

networks:
  wp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
