services:
  db:
    image: mariadb:12.3@sha256:b1c7bf836e64ed9406a8984af29509f40089d55cea14b32f12c4726a1f17104b
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      wp:
        ipv4_address: 172.25.0.3

  wordpress:
    image: wordpress:apache@sha256:6d37018d26165824c0dfb5d612e205c70adf760fed9c614187d18091646c9e31
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      wp:
        ipv4_address: 172.25.0.2
    volumes:
      - .:/var/www/html/wp-content/plugins/ww-yubico-otp

volumes:
  db:

networks:
  wp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
